### ISSUE TITLE
Pre-Processing Buildzoom Business Names

### ISSUE THREAD

**Issue by jcdavis56** [annitodd/PhoenixDataRepo#40]
**Note: For a detailed discussion of the Buildzoom data see issue #18. This issue is specific to the pre-processing of builder names.**

# Summary 

Per a discussion with Robert on 06/30, we may be able to use the contractor_id to help identify production builders. According to the data dictionary from Buildzoom, they assign a contractor ID for each unique business. However, there are multiple cases where the same name ("Lennar" for example) is associated with multiple contractor ID's. There does not seem to be a consistent pattern between contractor ID and any other geographic variables such as zipcode. I am currently exploring this issue more in depth, so our approach might change if we find anything. 

# How to handle NA values 

A queston for @annitodd and @wolske 

One of the other issues is that contractor ID is often missing from the data. The same permit number and property ID will often have the contractor listed for a few observations but not all, or sometimes the contractor ID is just missing entirely. How should we approach handling the missing data? Is this something we should impute using a fill option? We could do an exact match and fill the missing data with an exact match of the builder name? The obvious drawback would be overwriting existing data. However, since this was a label assigned by Buildzoom, we should not lose any information.  

# Tasks

- [x] Determine if contractor ID can be linked to any particular variable or pattern 
- [x] Identify potential reasons why contractor ID might be missing

~@RobBot00 anything to add or something I might have missed?~

# Pre-Processing Methodolgy

Major Goal: Determine what is the production builder associated with a property where solar is installed. 

## Description of Problem 

There are two ways we could accomplish our goal. We could a) begin with solar permits and search for builders from there or b) limit our search by starting with builders and then search for solar permits 

The major issue with filtering via solar permits is that rooftop permits are often very difficult to identify. Some contain keywords such as "rooftop" but others will contain no description of the system type. This means that we might lose a large number of observations which do not fit neatly into search criteria. Another significant obstacle is the number of permits that we would have to sort through. There are roughly 4 million permits in the "solar installation" project type and another 1 million  in "electrical work" (solar permits often appear as electrical work as well), so we would begin our search with roughly 5 million permits. 

The alternative is to try and identify the builders first and then search for builders have have done rooftop solar. We have our list of roughly 350 names (likely going to be more since we will be adding the subsidaries). We could potentially collapse the data as much as possible and use the fuzzy matching algorithim to identify builders. This ~ should ~ (emphasis on should) significantly reduce the number of permits to sort and identify.  

Detailed steps below and will be updated as this issue evolves

## Steps

1) Use Contractor Id to identify builders 
~a) First cut: subset BZ data to include only the observations where we have a contractor ID~
a) First cut: limit permits to only the most recent permit pulled which is grouped by permit number and business name (why? We know there are often duplicates permits which would inflate our count of permits for each contractor_ID)
b) create a new column and fill missing contractor IDs who match other names with our own version of the ID 
c) collapse easy to identify builders into a single entry
2) Identify builders in subsetted data 
a) Arrange by the count of number of permits in descending order. 
~b) We can make a third cut at X number of observations (number to be determined later) (i.e. Contractor IDs with less than X permits, we ignore) (Why? This limits the size of the data we need to manually clean)~
~b) Make a third cut and remove any observations that have a total count of less than two. This limits the size of the data that needs to be manually cleaned and allows us to remove roughly 20k observations which are likely not production builders~
c) Perform fuzzy name matching between list of unique builder names and subsetted data to identify which of remaining business names are builders. (Why? Well doing manual cleaning is impractical [see the count below, there are over 24,000 records with more than 20 permits] We use fuzzy name matching to help sort the data to string matches that are more likely to be builders) 

![image](https://github.com/annitodd/PhoenixDataRepo/assets/94181610/2a125e51-1905-4b67-8439-96073045fcc0)

3) Check results of fuzzy matching and identify builders 
a) Manually check results of name matching algorithms and make decisions about which names are properly matched
b) Create dummy that indicated whether business name has been cleaned

# Tasks related to identifying builders via fuzzy matching 

- [x] Subset data to be used with name matching 
~- [x] identify a reasonable threshold for the number of permits to make the cut mentioned in step 2.b~

# Summary of Updates

07/18/2023: removed the n>2 operation, create new column to identify the contractor IDs that we fill, collapse major builder names
- Removed the n>2 filter because our BZ data is all permits which are affiliated with a solar permit. Still possible for a production builder to have at least one or two solar permits so we want to be sure that we capture them. 

07/24/2023: 
- automated the script to search for all parent company names in the cross walk 
- created new variables to identify exact string matches, pre-identified builders, and false matches
- total time to run script is roughly 30 minutes

# Summary of final script 

file name: "PHX_BZ_01_pre process builder names_full_data.R" 

total run time: roughly thirty minutes

This script was built on a lot of trial and error, so including a summary here in case anyone has to decipher what I was trying to do. 

Essentially, this final script should automate any and all pre-processing now or in the future if the list of builder names change in the crosswalk file (our list of production builder names). 

The first section of the script fills missing contractors IDs if there is an exact match on the business name. All missing IDs take the value of the ID above it. THe ID will remain as NA if there are no other matching business names with a contractor ID. I then limit all permits to only the most recent status to cut out the redundancy. Finally, we collapse everything down to builder names, contractor ids, and a count of the observations for those groups (this happens at the beginning to make the rest of the script run faster.) 

I then do basic pre-processing operations such as removing whitespace, puncutation, and stop words. All of these names are stored in the c_BUSINESS_NAME column. I do this for both the crosswalk and the bz data. 

It gets more complex when we introduce the pattern matching. I use the simplified business name from the crosswalk data to search for companies in BZ. All of the builder strings from the crosswalk are stored in a vector which is put through a for loop. I use grepl here to identify observations where our pattern matches those found in the BZ data and changes those names to the simplified version from the crosswalk. I do this so that we can easily join the two later on. It also only searches for complete words (avoids capturing Mr. Lennard Lopez)  and has an optional character for s to capture plural names (KB homes or KB home). 

Finally, I create a potential builder column in the crosswalk which is a dummy variable = 1. Then I join the BZ data with the crosswalk. Since we replaced all the matching patterns in the BZ data, they should have the same name as the clean business name in the crosswalk. We can join on this column so that we also have the represenative builder name in our final collapsed data. 

The last step is identifying false matches, true positives, and creating a dummy variable for each. This step is done manually but all work happens in the script. Among the roughly 300 variations identified, only 17 of these are false matches. 

# Description of variables created 

The final "collapsed dataset" for the pre-processing has eight variables 

1. BUSINESS_NAME - the original business name from BZ
2. c_BUSINESS_NAME - a clean business name with stop words removed 
3. representative_builder_name - the common name from the crosswalk 
4. CONTRACTOR_ID - original, unchanged contractor ID 
5. c_CONTRACTOR_ID - a "filled" contractor ID with labels indicating which values were filled
6. exact_match - a dummy indicating if a variabe had an exact match with a business name 
7. potential_builder - a dummy indicating a string which matched one of our builders from the crosswalk
8. false_positive - a non-production builder which was falsely identified when we joined the cross walk
9. true_positive - dummy indicating a correclty identified builder
10. identified - a final dummy indicating that a match was identified as a true_positive or  a false_positive
