### ISSUE TITLE
Pre-Processing Buildzoom Homeowner Names

### ISSUE THREAD

**Issue by jcdavis56** [annitodd/PhoenixDataRepo#59]
# Summary

A similar exercise to issue #40. We want to see if we can identify builders among homeowner names with exact / pattern matching methods. Much of the process for homeowner names has already been described in #40 but will also be summarized (more briefly) here. 

In total we pick up about 1000 variations pre processing the homeowner name which is associated with roughly 72k permits. 

# Tasks to be completed 

- [x] Preform an exact match of representative builder name from our crosswalk on homeowner name
- [x] adapt previous business name code to identify builders among homeowners 
- [x] Identify true / false positive matches in excel 
- [x] join identified matches to full bz data
- [x] export data to be used in the matching algorithim

# Methodology 

There are two scripts which clean and join the bz data 

1. PHX_BZ_01_pre processing of homeowner name
2. PHX_BZ_02_dictionary joined to bz

The first collapses the data down to homeowner names only. I then clean the columns just as we did in #40. This includes removing white space, all lowercase, removal of punctuation, and removing major stop words. These "clean" entries are contained in the c_HOMEOWNER_NAME column. I then apply the same operations to the crosswalk file to begin identifying builders 

I then take our crosswalk along with their "clean" names and search for matching patterns in the HOMEOWNER name. The pattern used is for whole words with an optional s, so a "lennard lopez" will not be captured when searching for Lennar. However, this also means that we might miss a "len nar" if there happens to be a typo which will hopefully be picked up in our fuzzy matching algorithm. 

I then replace the clean homeowner names with the string contained in the crosswalk so that they can easily be merged. Finally we create a dummy column for these potential identified builders. **NOTE**: a potential builder == 1 just means that you have a pattern which matches a name contained in our crosswalk. It does not imply that you are a builder. 

Finally, I export the file PHX_02_data for true positive identification which contains only potential builders. This dataset is then reviewed in excel to manually identify true  / false positive matches as well as false negatives. 

The second script joins the manually identified dataset  (PHX_01_pre processed bz data for matching algorithim contained in the analysis_output folder in box) to the raw bz data. This gives us a clean dataset with all the original data, the pre processed homeowner name, their representative builder name, true positive, false positive, and false negative dummies. FInally, there is an identified_builder_homeowner column which indicates that a potential builder was manually reviewed. 

Script run time depends on your computer. Robert can run the script in roughly 20 minutes, but my computer takes approximately an hour and a half. Just something to keep in mind if it takes awhile. 

# Timeline of Updates / Changes

**Comment by RobBot00** [comment]
This task is complete.
