### ISSUE TITLE
Pre-Process the CHEESE data 

### ISSUE THREAD

**Issue by jcdavis56** [annitodd/PhoenixDataRepo#62]
# Summary 

We love data that is already most clean. Much of the pre processing is very straight forward. We are able to manually identify roughly ~220k~ 368k of the total observations in the CHEESE data and 363k of these observations are true positive builders.  These scripts run very quickly. Should only take a few seconds for both. 
# Tasks 

- [x] match the pre-existing "cleaned" names to our represenative builder names from the cross walk 
- [x] create a dictionary for a phx_name based on pre-identified builders in cheese
- [x] identify builders not contained in the clean column 
- [x] join representative names to newly identified matches 

# Methodology

The scripts are split into a cleaning file and a joining file. 

1. PHX_CHZ_01_pre process condensed cheese data
2. PHX_CHZ_02_join true positives to clean chz data

All the pre processing includes the same steps as #59 and #40 . Both the seller1fullname and builder columns are all changed to lowercase, removal of white space, punctuation, and removal of major stop words. I also replace some of the pre-identified builder names to match with the clean names contained in the crosswalk.

The major difference between this script and the other issues is that we create a dictionary for the previously identified builders in cheese. We simply take the cheese name and assign a corresponding name in the phx_name column which matches to our crosswalk of representative names. There are roughly 120 builders previously identified, but many of these are not present in our crosswalk or list of subsidiaries. 

We then join the represenative builder names to the full cheese data and export a file to identify the true / false positive matches. All identification and creation of dummies occurs manually in excel. The previous work done to identify builders makes this step much easier. I only had to check 765 observations for true positive matches. 

The second file simply joins the identified matches to the full cheese data. The final data set "PHX_04_final pre process CHZ data" (located in analysis_output in box) contains all the previously created "clean" columns as well as dummies for true positive, false positive, false negative, and an identified builder homeowner column.  

# How solar status is determined in Cheese 
**_WORK IN PROGRESS_**
Solar status is based on solar install date in TTS compared to house sale date in SBL being within a year before/after the sale date and being tagged as new construction in SBL

**Comment by RobBot00** [comment]
In reference to this observation from Joshua:
> Non overlapping names from cheese not found in crosswalk
>
> I have been using the "/02b_Secondary_Data/Compiling Top Builders/3. analysis_output/PHX_CTB_01_Builder name crosswalk.csv" file so let me know if that is not the right one

Basically, LBNL's list of builders for their analysis does not fully overlap with out list of production builders. In short, we are not missing any major production builders. Most of the non-overlapping builders are modular/custom/niche builders, real estate developers, and mortgage companies. There were a few entries that LBNL have that we don't that may be worth incorporating into our analysis:

**Cal Atlantic Homes** _was_ actually a very large builder (top 10). Through they were acquired by Lennar in 2018. Our solar data in BZ overlaps with this so it may be wise to search for Cal Atlantic in our name matching algorithm. 

**Centex** is a subsidiary of Pulte Group. 

**Del Webb** is a subsidiary of Pulte Group. 

**Greystone Homes** is a production community builder in IL. 

**JKB Living** is a production community builder in CA. 

**Pardee Homes** is a subsidiary of Tri Pointe Homes.

**Patterson Homes** is a production community builder in UT. 
 
**Quadrant Homes** was acquired by Tri Pointe Homes in 2014.

**Ryland Homes** merged with **Standard Pacific Homes** to form **CalAtlantic** in 2015, which was then acquired by Lennar in 2018.

**Western Pacific Housing** is a subsidiary of DR Horton. 

**William Lyon Homes** is a subsidiary Taylor Morrison.

I reviewed the analysis notes from Ben and Grace; on page 255 their is reference to where these builders come from: 
[2020 Builder magazine Top 100](https://www.builderonline.com/builder-100/builder-100-list/2020/) and [2020 Builder magazine West Regional Top 100](https://www.builderonline.com/builder-100/builder-100-list/2020/?rg=West). The national list should pretty much fully overlap with ours as we are using the 2022 version of this list, and for the most part it does. The regional list contains many larger custom builders along the west coast, which would explain why most of the builders that do not overlap between LBNL and our set are custom builders. 

@wolske For the builders I list above, do you think it's worth adding them into our analysis? This would mean creating a mapping between a companies pre-merger/pre-acquisition name and their current name, and adding it to our analysis. I estimate this would take ~1 - 3 hours to do this; @eshanprashar, would you agree?
